
sample_rate: 8e6
total_samples: 16000
selected_samples: 8000

carrier_freq: 2e6
carrier_peak_to_peak: 1.0

ma_bottom: 0.5
ma_top: 1.0

mf_bottom: 1.0
mf_top: 5.0
F_max: 2000

h_bottom: 2
h_top: 5

noise_factor: 0.1

wave_jsonl_path: config/waves_base_test.jsonl

output_dir: datasets/sim-AD2-test
dataset_name: dataset.pt
device: cuda